[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[terminal.shell]
args = ["--login"]
program = "/opt/homebrew/bin/fish"

[window]
blur = true
decorations = "buttonless"
opacity = 0.8
option_as_alt = "OnlyLeft"

[window.padding]
x = 15
y = 30

[cursor]
# Set to false to disable completely
smooth_motion = true
# 0.0 = cursor is not moving, 1.0 = cursor moves instantly
smooth_motion_factor = 0.8
# 0.0 = broken, 1.0 = cursor shape is unaffected by movement
smooth_motion_spring = 0.8
# Limits how the cursor size may change
smooth_motion_max_stretch_x = 2
smooth_motion_max_stretch_y = 2
# Override "block" cursor if you don't like how it looks in this fork
# I prefer "underline"
# block_replace_shape = "underline"

